### ISSUE TITLE
Running autoconf to create configure script

### ISSUE THREAD

**Issue by pppbb** [roderickc/wine-vulkan#13]
What  arguments should i pass to autoconf to create configure script? After compiling without running autoconf first i get error in wine that it cannot connect with disk management.

**Comment by roderickc** [comment]
Autoconf doesn't need anything. However, configure script will try to detect what headers you have on your system and based on that enable/disable features. There is no difference in that regard between wine-vulkan and regular wine.

The number of dependencies is large and highly dependent on your Linux distribution. There should be instructions on compiling Wine and what dependencies you need to install for various distributions on the Wine wiki:
https://wiki.winehq.org/Building_Wine
https://wiki.winehq.org/Category:Distributions (should have Ubuntu, Fedora, ...)

**Comment by ssorgatem** [comment]
Is there anything specific to wine-vulkan that I should enable?

When I try to build it like regular wine... it doesn't build winevulkan.dll for some reason...

**Comment by roderickc** [comment]
It should not be needed anymore to run autoconf as most code including configure is now in Wine, so even on wine-vulkan there is no need to recreate the configure script.
