### ISSUE TITLE
Probably typo in the Wine-Vulkan documentation 

### ISSUE THREAD

**Issue by zefkerr** [roderickc/wine-vulkan#16]
Now:
If on 64-bit also add a line to load the json file for 32-bit:

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432NodeKhronos\Vulkan\Drivers\]
"C:\Windows\winevulkan.json"=dword:00000000

But probably need \ here Wow6432Node\Khronos
If on 64-bit also add a line to load the json file for 32-bit:

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Khronos\Vulkan\Drivers\]
"C:\Windows\winevulkan.json"=dword:00000000

**Comment by roderickc** [comment]
Thanks, fixed.
