### ISSUE TITLE
Error on winevulkan.dll loading

### ISSUE THREAD

**Issue by gillg** [roderickc/wine-vulkan#19]
As now this project is part of wine 3.4, I follow up a submitted bug on wine bugzilla.
Maybe someone have more experience on this here.

https://bugs.winehq.org/show_bug.cgi?id=44775

**Comment by gillg** [comment]
Resolved : it was a "corrupted" wine build from PlayOnLinux repo, which is not compiled with vulkan support. Try to compile wine 3.4 yourself

**Comment by roderickc** [comment]
Marking as fixed.
