### ISSUE TITLE
Compile error -Wno-packed-not-aligned

### ISSUE THREAD

**Issue by SveSop** [roderickc/wine-vulkan#2]
Trying to compile this on Ubuntu 14.04 with gcc 7.2.0 and i get

`../../../wine-vulkan/dlls/winevulkan/vulkan.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-packed-not-aligned’
make[1]: *** [vulkan.o] Error 1`

`checking whether the compiler supports -Wno-packed-not-aligned... yes`

So... should i disable this with some sort of CFLAG or something? :)

**Comment by roderickc** [comment]
I'm honestly not too sure. I only made minor changes to the build system just enough to build dlls/winevulkan and set a setting in config.h. For the rest it is just the wine configure script, which you need to pregenerate and you probably did.

When I glanced over configure.in it seems to do some checks to see if compiler flags are supported by the compiler, which is also why you see 'Checking whether the compiler supports ....'. I don't know why this passes, but ultimately gcc is unhappy. In any cases it looks like it is just about silencing warnings.

Easiest way to bypass it is just get rid of the relevant WINE_TRY_CFLAGS line in configure.in. Rerun autoconf and compile again.

**Comment by SveSop** [comment]
Just by quick glance, it seems your build is on Wine-3.0-rc4 yes?

I had no problems compiling the regular wine-3.0-rc4 when it was released, so cant really tell for sure other than vulkan.c has some weird option that is not happy with -wno-packed-not-aligned option.

Regular wine compiles fine after running the configure script. The only extra flags i pass to the configure script is 'CFLAGS=-march=native -O2' . Maybe your vulkan source does not like any optimization? (Although it might be that these are default anyway?)

I tried to just edit the config file so that this check did not pass this option to gcc, and that led to another failure in compiling with something else not vulkan related tho.

Will clean out my VM and recreate it tonight and do a compile of wine-dev again just to make sure its not broken by some other stuff tho.

**Comment by SveSop** [comment]
Seems as it was not compiling with newer version of libvulkan1. I had the libvulkan1 1.0.61.1 installed from a PPA, but downgraded to 1.0.51.0 by installing .deb manually, and the compile went through.

I compile in a VirtualBox VM, cos then i can fiddle around with packages and whatnot and can easily "clean house" by restoring a backed-up disk file. However, on my "real" install, i am still using libvulkan1 1.0.61.1 from the graphics-drivers PPA.. 

Is this the reason things like cube.exe crashes you think?

**Comment by roderickc** [comment]
A few questions first. Are you using 32-bit or 64-bit version of cube? What graphics drivers are you using? Do you really have vulkan drivers installed, libvulkan is just a loader. Does vulkaninfo.exe work?

For me cube works fine in 32-bit and 64-bit, so do games like the new Doom, Wolfenstein and Talos Principle.

**Comment by SveSop** [comment]
I have tried both versions. The 64 bit one gives a `Page fault on read access`, while the 32 bit one indicates that no 32 bit ICD is found. Do i need libvulkan1:i386 in ubuntu?

I am using nVidia 387.34 driver, and libvulcan1 1.0.61.1 from "Graphics drivers PPA". Ubuntu 14.04. I can run vulkan-smoketest in ubuntu with no error.

Vulkaninfo in ubuntu gives a lot of capabilities.. and lists:
`GPU0
VkPhysicalDeviceProperties:
===========================
	apiVersion     = 0x400038  (1.0.56)
	driverVersion  = 1623752704 (0x60c88000)
	vendorID       = 0x10de
	deviceID       = 0x13c2
	deviceType     = DISCRETE_GPU
	deviceName     = GeForce GTX 970`

Vulkaninfo in Wine gives a list of registry keys, and the rest is black/cant read when i scroll the window.

If i run "VulkanCapsViewer" from [http://vulkan.gpuinfo.org/download.php](url) in wine, it gives loads of capability info. More or less the same as with wine-staging, but wine-staging will have 2 error messages upon start, while wine-vulkan does not.

**Comment by roderickc** [comment]
To use the 32-bit cube.exe and other tools you would need a 32-bit
libvulkan1 and of course 32-bit nvidia libraries in your case as well.

Would you be able to share your crashdumps? I'm curious what exactly is
failing. Also try to set WINEDEBUG=+vulkan to get some more logging (e.g.
WINEDEBUG=+vulkan wine appname.exe). I must say I haven't tested on Nvidia
yet, but AMD (radv) and Intel (anv) seem to work fine so far.

**Comment by SveSop** [comment]
[playonlinux.log](https://github.com/roderickc/wine-vulkan/files/1623037/playonlinux.log)
The debug log from a crash of 64bit cube.exe.

I am kinda SOL when it comes to 32bit libvulkan1 for my 14.04 distro sadly.. I tried to "cheat" and install the 16.04 libvulkan1 libraries, but that did not work when trying eg. vulkan-smoketest.. Some error with libstdc++6.
And cross compiling 32bit libs is a pita on Ubuntu, but i have set up a own VM just for that and wine.. dunno if i could use that to compile my own libvulkan libraries tho..

**Comment by roderickc** [comment]
I had a quick look and the code is crashing in libvulkan1, but that code be
because I'm doing something wrong (maybe Nvidia has different behaviour).
Although it could also be your more outdated distribution. Though libvulkan
is mostly just a passthrough layer between application and the graphics
drivers its vulkan ICD.

**Comment by SveSop** [comment]
It would not be the first time nVidia proprietary drivers do something NOT appropriate when it comes to things like that... :)

I might try compile some of the VulkanSDK examples in linux and see how they behave tho..

**Comment by SveSop** [comment]
With wine-staging-2.18 and their Vulkan implementation, the 64-bit cube works. Dont have any of the Vulkan games available, so kinda hard to test things like Doom and such tho.

Wine-3.0-rc5 i get no vulkan support.

**Comment by roderickc** [comment]
I will try an Nvidia gpu maybe later this weekend. As I said it is likely a bug on my end, I just have no clue at all where.

**Comment by jozefkucia** [comment]
`wine_vkAllocateCommandBuffers()` doesn't initialize all fields of `VkCommandBufferAllocateInfo`, `sType` and `pNext` are not initialized.

Properly initializing those fields fixes crashes when running with Nvidia drivers.

**Comment by roderickc** [comment]
Thanks for letting me know. I was about to test tonight with a 1070 after
fixing a few other issues.

**Comment by roderickc** [comment]
I confirmed on Nvidia this was the issue. I made changes and pushed (force push as I edited the original commit which added CommandBuffer support).

**Comment by SveSop** [comment]
Cloned the repo and recompiled. I gotz da cube!! :)

Gonna fiddle around with it and do some tests :) Thanks for the fix! Good work!
