### ISSUE TITLE
Add support for VK_EXT_vertex_attribute_divisor

### ISSUE THREAD

**Issue by libcg** [roderickc/wine-vulkan#21]
This is required for https://github.com/doitsujin/dxvk to efficiently run some games, such as GTA V.

**Comment by roderickc** [comment]
I have added some initial 1.1 support. It still needs some cleanup, but it is likely functional. I don't have any 1.1 software to test though.

**Comment by libcg** [comment]
Thanks a lot. Looks like the bit to enable the extension is there now (see https://github.com/doitsujin/wine-hacks/blob/master/vulkan-enable-extensions.patch). Closing.
