### ISSUE TITLE
Cannot run Wolfenstein 2

### ISSUE THREAD

**Issue by mondalaci** [roderickc/wine-vulkan#3]
Gave your repo a try, just as you asked in the Wolfenstein 2 wine thread.

I get this:

```
laci@spark ~/download/wine-vulkan/tools $ ./winewrapper C:\\Program\ Files\ \(x86\)\\Wolfenstein\ II\ The\ New\ Colossus\\NewColossus_x64vk.exe
...
004e:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0046:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
004e:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0029:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0029:fixme:dwmapi:DwmIsCompositionEnabled 0x6dbd1518
0052:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0x9e65c0, init_notify 0, handle 0x12df9f0): stub
wine client error:0: version mismatch 547/544.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
wine: configuration in '/home/laci/.wine' has been updated.
0009:err:module:import_dll Library vulkan-1.dll (which is needed by L"C:\\Program Files (x86)\\Wolfenstein II The New Colossus\\NewColossus_x64vk.exe") not found
0009:err:module:attach_dlls Importing dlls for L"C:\\Program Files (x86)\\Wolfenstein II The New Colossus\\NewColossus_x64vk.exe" failed, status c0000135
laci@spark ~/download/wine-vulkan/tools $ wine: Unhandled page fault on read access to 0x7fabf8625540 at address 0x7fabfa6acfc3 (thread 004c), starting debugger...
004c:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 31 96") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger
```

Wolfenstein 2 was running fine a while ago with the Vulkan patches of the aforementioned thread, but audio was always choppy, so I only tried it for a couple of minutes. Any help is welcome.

**Comment by roderickc** [comment]
There are a couple of issues. Let me go over them one by one.

1. "wine client error:0: version mismatch 547/544." this is an indication that you have a mixture of wine versions on your system. This will result in strange undefined behaviour. You could uninstall the other wine copy or run wine-vulkan just from the source directory.

2. You need to install the vulkan runtime to obtain vulkan-1.dll and you also need to create winevulkan.json and set a registry option. See the README.md or the website of this project.

Let me know how it goes.

**Comment by mondalaci** [comment]
Managed to resolve 1. As for 2, I set up almost everything but don't know how to obtain vulkan-1.dll. I fetched VulkanSDK-1.0.65.1-Installer.exe and executed it with wine but it segfaulted:

```
laci@spark ~/download $ /home/laci/download/wine-vulkan/tools/winewrapper VulkanSDK-1.0.65.1-Installer.exe 
wine: Unhandled page fault on read access to 0x7f44fdc12540 at address 0x7f44ffc99fc3 (thread 003f), starting debugger...
003f:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 34 88") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger
```

**Comment by roderickc** [comment]
Hm, I'm not sure. I haven't tried the installer recently. I would try an
older version. Technically I'm at version 1.51 so you can go far back if
needed. Though steam might be providing the dlc as well. For wolfenstein
you need the 64-bit dll

**Comment by mondalaci** [comment]
Please attach the dll here because 1.51 segfaults for me too.

**Comment by roderickc** [comment]
[vulkan.tar.gz](https://github.com/roderickc/wine-vulkan/files/1652888/vulkan.tar.gz)

Try that. The lib64 folder contains the library you need. Honestly I wonder if something is wrong with your wine setup as the real installer works fine for me. If you don't use the installer you may miss other registry keys needed.

**Comment by mondalaci** [comment]
I copied `vulkan.tar.gz:/lib32/vulkan-1.dll` as `~/.wine/drive_c/windows/system32/winevulkan.dll` and get:

```
laci@spark ~/download/wine-vulkan/tools $ ./winewrapper C:\\Program\ Files\ \(x86\)\\Wolfenstein\ II\ The\ New\ Colossus\\NewColossus_x64vk.exe 
0009:err:module:import_dll Loading library vulkan-1.dll (which is needed by L"C:\\Program Files (x86)\\Wolfenstein II The New Colossus\\NewColossus_x64vk.exe") failed (error c000007b).
0009:err:module:attach_dlls Importing dlls for L"C:\\Program Files (x86)\\Wolfenstein II The New Colossus\\NewColossus_x64vk.exe" failed, status c0000135
```

**Comment by roderickc** [comment]
You only need to copy vulkan-1.dll the 64bit one as wolfenstein is a 64bit
game. You can put it in the appropriate system32 folder for 64bit or in the
wolfenstein executable folder. Don't rename the file.

Next is the registry option see the instructions, which is what tells
vulkan-1.dll how to load winevulkan.dll.so. That's what will enable my code

**Comment by mondalaci** [comment]
I followed your instructions, and got a crash dump. This is way more problematic than I anticipated. I appreciate your work, but I don't have time for this. Good luck, and thank you!
