### ISSUE TITLE
Vulkaninfo - VK_ERROR_INCOMPATIBLE_DRIVER

### ISSUE THREAD

**Issue by mmcnutt** [roderickc/wine-vulkan#9]
I have compiled from master following the instructions

Installed latest vulkansdk
created json file and reg keys

vulkaninfo.exe returns

`Vulkan API Version: 1.0.65

ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode ©
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode ¿
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode _
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 0
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode _
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 9
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 1
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode ¿
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode ÿ
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode Ç░
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode ©
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode ¿
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode _
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 0
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode _
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 9
ERROR: [loader] Code 0 : loaderGetRegistryFiles: failed to open DevNode 1
ERROR: [loader] Code 0 : Failed to open dynamic library "c:\windows\system32\winevulkan.dll" with error 1114
Cannot create Vulkan instance.
C:\VulkanSDKBuild\workspace\LoaderAndValidationLayers\demos\vulkaninfo.c:703: failed with VK_ERROR_INCOMPATIBLE_DRIVER`

native vulkan games like Talos principle work, as did doom 2016 before I removed wine staging and compiled this. I am however running mesa 18.0RC2 - if that is an issue?

cube.exe returns unable to create vulkan instance

thanks for your help

**Comment by roderickc** [comment]
I think I know what is wrong. Have a look at my last comments on older issue: https://github.com/roderickc/wine-vulkan/issues/7. Basically winevulkan will fail to load if winex11 doesn't have vulkan compiled in. This likely happened, because the configure script wasn't recreated.

**Comment by mmcnutt** [comment]
the configure script is recreated with autoconf, correct?

I have attempted on another machine, same error, so obviously I am missing something

did a dnf build-dep wine to get my build dependencies 

my process was as follows 

'git clone <repo>
cd /wine-vulkan
autoconf
mkdir wine64
mkdir wine32
cd wine64
../configure --enable-win64
make
cd ../wine32
PKG_CONFIG_PATH=/etc/lib ../configure --with-wine64=../win64-build
make'



I then sudo make install both builds (so it becomes my system version of wine)

**Comment by roderickc** [comment]
See the other thread. In particular check if config.h has vulkan set. In
addition check if you have the libraries.

**Comment by mmcnutt** [comment]
this was the issue the libvulkan.so.1 was not defined for the w32 bit build

all working now, thank you
